version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with file watching in Docker on some systems
    networks:
      - react-network
    command: npm start

networks:
  react-network:
    driver: bridge
